let level =
	"abbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbc"
+	"f                                      f"
+	"f abbbbq pbbbbbbbbbbbbbbbbbbbbbbbbbbbc f"
+	"f f                                  f f"
+	"f f abbbbbbbbbbbbq pbbbbbbbbbbbbbbbc f f"
+	"f f i                              f i f"
+	"f f   abbbbbbbbbbbbbbbbbq pbbbbbbc f   f"
+	"f f d f                          f f d f"
+	"f f f f abq pbbbbbbbbbbbbbbbbbbc f i f f"
+	"f f f f f                      f f   f f"
+	"f f f i f abbbbbbbbbq pbbbbbbc f f d f f"
+	"f f f   f f                  f f i f f f"
+	"f f f d f f abbq pbbbbbbbbbc f f   f f f"
+	"f f f f f f f              f f f d f f f"
+   "f f f f f f f eeee gg eeee f f f f f f f"
+   "f f f f f i f eeee gg eeee f f f f f f f"
+   "f f f f f   f eeee gg eeee f f f f f f f"
+   "f f f i f d i eee      eee i f f f f f f"
+   "f f f   f f                  f f i f f f"
+   "f f f d f f d ggg      ggg d f f   f f f"
+   "f f f f f f i ggg      ggg i f f d f f f"
+   "f f f f f f                  f f f f f f"
+   "f f f f f f d eee      eee d f f f f f f"
+   "f f f f f f f eeee gg eeee f f f f f f f"
+   "f f f f f f f eeee gg eeee f i f f f i f"
+   "f f f f f f f eeee gg eeee f   f f f   f"
+	"f f f f f f f              f d f f f d f"
+	"f f f f f f kbbbbq pq pbbbbm f f i f f f"
+	"f f i f f f                  f f   f f f"
+	"f f   f f kq pbbbbbbbbbbq pbbm f d f f f"
+	"f f d f f                      f f f f f"
+	"f f f f kbbbbbq pbbbbbbbbbbbbbbm f f f f"
+	"f f f f                          f f i f"
+	"f f f kbbbbbbbbbbbbbbq pbbbbq pbbm f   f"
+	"f f f                              f d f"
+	"f f kbbbbq pbbbbbbbbbbbbbbbbbbbbbbbm f f"
+	"f f                                  f f"
+	"f kbbbbbbbbbbbbbbq pbbbbbbq pbbbbbbbbm f"
+	"f                                      f"
+	"kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbm"


levels = new Array();

levels.push(level);

